### ISSUE TITLE
Something went wrong?

### ISSUE THREAD

**Issue by yareg** [kidk/felt#16]
I've installed felt, 

% python --version
_Python 2.7.10_

% python ./test.py

_----------------------------------------------------------------------
Ran 0 tests in 0.001s

OK_

% ls
_examples  LICENSE  main.py  phantomjs  README.md  test.py  tests  Vagrantfile  VERSION  worker.js_

Finally, I try
% python ./main.py --verbose --threads 1 --debug  examples/basic.json
_################################
        Felt (alpha)
###### 

{'test': False, 'threads': 1, 'verbose': True, 'scenario': 'examples/basic.json', 'debug': True, 'userAgent': None, 'maxTime': 0, 'screenshot': False, 'browser': 'phantomjs'}
###### 

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/src/Python-2.7.10/Lib/threading.py", line 810, in **bootstrap_inner
    self.run()
  File "/usr/src/Python-2.7.10/Lib/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "./main.py", line 216, in execute
    stderr=subprocess.STDOUT
  File "/usr/src/Python-2.7.10/Lib/subprocess.py", line 710, in __init**
    errread, errwrite)
  File "/usr/src/Python-2.7.10/Lib/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

^CTraceback (most recent call last):
  File "./main.py", line 301, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./main.py", line 70, in main
    worker.run(scenario, options)
  File "./main.py", line 188, in run
    time.sleep(0.25)_

Using _python main.py_ instead of _python ./main.py_ has no effect. What is wrong?

**Comment by hmedhat** [comment]
did you install phantomjs?

**Comment by yareg** [comment]
Oh, really, it's my fault. Thank.
