### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by gthomas2** [kidk/felt#23]
(Running on OSX Sierra with phantomjs 2.1.1)

I have tried phantomjs as an executable in my path AND
also directly as a binary inside the felt folder.

When I run

python main.py --verbose examples/basic.json

I get:

```################################
	Felt (alpha)
################################
['phantomjs', 'worker.js', '1', '[{"action": "open_url", "value": "http://felt.sava.be/"}, {"action": "click", "selector": "#navbar > ul > li:nth-child(2) > a"}, {"action": "open_url", "value": "http://felt.sava.be/login.php"}]', '{"debug": false, "userAgent": null, "verbose": true, "screenshot": false}']
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/gthomas2/Development/felt/core.py", line 143, in execute
    stderr=subprocess.STDOUT
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 709, in __init__
    errread, errwrite)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1326, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```

I fixed this by changing
  File "/Users/gthomas2/Development/felt/core.py", line 140
```
shell=True,
```
Is there anything bad about doing this?

**Comment by gthomas2** [comment]
Non-issue : Needed a new terminal to get new path.

**Comment by kidk** [comment]
Hi @gthomas2 

Glad you were able to find the solution. `shell=True', does indeed allow you to use Felt without adding it to the path, but it causes a whole lot of other issues :smile:
